stages:
  - mirror

mirror_to_github:
  stage: mirror
  script:
    - git remote add github https://Momin9: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@github.com/Momin9/deploy-on-heroku.git
    - git checkout -b main
    - git fetch origin
    - git push github --mirror
  only:
    - main  # Adjust branch as needed