# Generated by Django 4.2.3 on 2023-10-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
